messages:
  start: "Здравствуйте. Меня зовут - Смартик. Я цифровой помощник международного онлайн-института психологии Smart.\n
Хотите подобрать обучающую программу или подробнее узнать про профессию психолога и онлайн-институт?\n
Напишите ваш вопрос в чат!
"

keyboard:
  add_profile: "Меню"
  edit_profile: "..."
