messages:
  start: "Здравствуйте. Меня зовут - Смарти. Я цифровой помощник международного онлайн-института психологии Smart.
\n\n
Я помогу вам подобрать обучающую программу по психологии. Напишите в чат “Хочу подобрать обучающую программу”. Также вы можете задать вопросы про наш институт, программы обучения или спросить о профессии психолога.
\n\n
Напишите ваш вопрос в чат!

"

keyboard:
  add_profile: "Меню"
  edit_profile: "..."
